name: CD Pipeline

concurrency: production

on:
  push:
    branches:
      - main
jobs:
  test1:
    name: Test elixir 1.14.0
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: '25.1'
          elixir-version: '1.14.0'
      - run: mix deps.get
      - name:
        run: mix test
  test2:
    name: Test elixir 1.14.1
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: '25.1'
          elixir-version: '1.14.1'
      - run: mix deps.get
      - name:
        run: mix test
